global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 1.0  #地图更新的频率
   publish_frequency: 0.0  #地图发布出来显示更新的频率
   static_map: true
   rolling_window: false  #当静态地图设置为true，rolling_window设置为false
   resolution: 0.05
   transform_tolerance: 1.0  #指定tf变换中能容许的数据延迟的时间，这里为1s
   map_type: costmap

   plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#   sonar_layer:
#     topics: ["/ultra_dist1","/ultra_dist2","/ultra_dist3","/ultra_dist4","/ultra_dist5","/ultra_dist6"]
#     no_reading_timeout: 1.0
    
