local_costmap:
   publish_voxel_map: true
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 5.0   #3.0
   publish_frequency: 3.0   #1.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.02  #local cost map resolution>=gmapping map resolution
   transform_tolerance: 2.0
   map_type: costmap

plugins:
 - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
 - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
 - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 
obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

sonar_layer:
  topics: ["/ultra_dist1","/ultra_dist2","/ultra_dist3","/ultra_dist4","/ultra_dist5","/ultra_dist6"]
  no_reading_timeout: 1.0
