local_costmap:
   publish_voxel_map: true
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 3.0   #3.0
   publish_frequency: 1.0   #1.0
   static_map: false
   rolling_window: true
   width: 8.0
   height: 8.0
   resolution: 0.03  #local cost map resolution>=gmapping map resolution
   transform_tolerance: 1.0
   map_type: costmap
