base_global_planner: navfn/NavfnROS
#base_local_planner: trajectroy_local_planner/TrajectoryPlannerROS
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},{name: rotate_recovery, type: rotate_recovery/RotateRecovery},{name: aggresive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

controller_frequency: 15
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   
    acc_lim_x: 1.0
    acc_lim_y: 0.0 # zero for a differential drive robot
    acc_lim_theta: 1.6

    max_vel_x: 0.6  #0.2
    min_vel_x: 0.2  #0.1 设置为很大的负值，这将允许机器人陷入一个环境中后退从而达到避障的目的；
    max_vel_y: 0.0  # zero for a differential drive robot
    min_vel_y: 0.0
    max_vel_theta: 1.0 #0.3
    min_vel_theta: -1.0  #0.15
    min_in_place_vel_theta: 0.4
    escape_vel: -0.1

    holonomic_robot: false
#GLOBAL TOLERANCE
    yaw_goal_tolerance: 0.2 # about 11 degrees
    xy_goal_tolerance: 0.3  # 20 cm
    latch_xy_goal_tolerance: true  #false

#FORWARD SIMULATION
    sim_time: 1.5  # 2   这里设置<=2.0会产生局限的性能，尤其是机器人通过狭小的通道；
    sim_granularity: 0.05  #It basically means how frequent should the points on this trajectory be examined；越小计算资源越多
    angular_sim_granularity: 0.025
    vx_samples: 10
    vy_samples: 0 # zero for a differential drive robot
    vtheta_samples: 20 #一般情况下vtheta_samples>vx_samples  20  40
    controller_frequency: 15

#TRAJECTORY PLANNER
    meter_scoring: true
    pdist_scale: 0.8  #0.8
    gdist_scale: 0.4  #0.4
    occdist_scale: 0.01   #0.1  越小越好，这样就不会在障碍物附近陷住
    oscillation_reset_dist: 0.2   #0.05    
    heading_scoring: false
    heading_lookahead: 0.1 #how far look ahead in meters in-place-rotation
    heading_scoring_timestep: 0.8
    dwa: true   
    publish_cost_grid_pc: false
    global_frame_id: odom
    simple_attractor: false

#OSCILLATION PREVENTION
    reset_distance: 4

#GLOBAL PLAN
    prune_plan: true

NavfnROS:
  allow_unknown: true
  recovery_behavior_enabled: true
  visualize_potential: true
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253
