obstacle_range: 2.5  #机器人检测障碍物的最大范围
raytrace_range: 3.0  #机器人检测自由空间的最大范围，意味着3m范围内，机器人根据传感器的信息，清楚范围内的自由空间
footprint: [[0.25,0],[0.177,0.177],[0,0.25], [-0.177,0.177], [-0.25,0], [-0.177,-0.177], [0,-0.25], [0.177,-0.177]]
robot_radius: 0.26
inflation_radius: 0.1  #distance from an obstacle at which costs are incurred for planning paths，障碍物的膨胀系数，机器人应该与障碍物保持的最
                       #小距离
max_obstacle_height: 0.8
min_obstacle_height: 0.65
cost_scaling_factor: 3  #  default 10 exponential rate at which the obstacle cost drops off 越小衰减曲线的斜率越小，这样障碍物就会分布在路径两端
#lethal_cost_threshold: 100 #
observation_sources: scan
scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
