local_costmap:
   publish_voxel_map: true
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 10.0   #3.0
   publish_frequency: 3.0   #1.0
   static_map: false
   rolling_window: true
   width: 10
   height: 10
   resolution: 0.03  #local cost map resolution>=gmapping map resolution
   transform_tolerance: 2.0
   map_type: costmap
