# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from xunjian_nav/Sensor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sensor(genpy.Message):
  _md5sum = "930310bf8f953403d26333dc05df3fb6"
  _type = "xunjian_nav/Sensor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 yawAngle
int32   leftEncoder
int32   rightEncoder
int32   vx
int32   w
"""
  __slots__ = ['yawAngle','leftEncoder','rightEncoder','vx','w']
  _slot_types = ['float64','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yawAngle,leftEncoder,rightEncoder,vx,w

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.yawAngle is None:
        self.yawAngle = 0.
      if self.leftEncoder is None:
        self.leftEncoder = 0
      if self.rightEncoder is None:
        self.rightEncoder = 0
      if self.vx is None:
        self.vx = 0
      if self.w is None:
        self.w = 0
    else:
      self.yawAngle = 0.
      self.leftEncoder = 0
      self.rightEncoder = 0
      self.vx = 0
      self.w = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_d4i.pack(_x.yawAngle, _x.leftEncoder, _x.rightEncoder, _x.vx, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.yawAngle, _x.leftEncoder, _x.rightEncoder, _x.vx, _x.w,) = _struct_d4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_d4i.pack(_x.yawAngle, _x.leftEncoder, _x.rightEncoder, _x.vx, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.yawAngle, _x.leftEncoder, _x.rightEncoder, _x.vx, _x.w,) = _struct_d4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d4i = struct.Struct("<d4i")
